# Generated by Django 3.2.12 on 2022-07-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_citizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='no_identification',
            field=models.IntegerField(),
        ),
    ]
