# Generated by Django 3.2.12 on 2022-07-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_citizen_no_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='no_identification',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
